Feature/view post
samra-pullflow/redwoodblog pull request #2
Opened 2024-01-03 05:24 UTC by samra-pullflow

2024-01-03 06:52 UTC, amnanwar requested changes

2024-01-03 06:52 UTC, amnanwar commented on api/src/lib/auth.ts
> +//  api/src/lib/post_manager -> db calls to create/update/delete/get post
dont need this comment here

2024-01-03 06:52 UTC, amnanwar commented on api/src/lib/post_manager.ts
> +import { db } from 'src/lib/db'
use relative imports

2024-01-03 06:52 UTC, amnanwar commented on api/src/lib/post_manager.ts
> +// postgresql://postgres:simplepw@localhost:5432/posts_db
we can remove this

2024-01-03 06:52 UTC, amnanwar commented on api/src/lib/posts.test.ts
> +import {
relative imports

2024-01-03 06:52 UTC, amnanwar commented on api/src/lib/posts.test.ts
> +import {
also this file should be called post_manager.test.ts

2024-01-03 06:52 UTC, amnanwar commented on api/src/services/posts/posts.ts
> +// postgresql://postgres:simplepw@localhost:5432/posts_db
not needed

2024-01-03 06:52 UTC, amnanwar commented on api/src/lib/post_manager.ts
> +export const posts: QueryResolvers['posts'] = () => {
no need for query or mutation resolvers in this file.
you can create an object literal with methods defined inside like

export const Post: {
getPost: () => {},
getManyPosts: () => {},
etc
}

and use these in your post service

2024-01-03 06:52 UTC, amnanwar commented on api/src/services/posts/posts.ts
>    return db.post.findUnique({
we shouldn't be doing any direct db calls in service, use methods from post_manager

2024-01-03 06:52 UTC, amnanwar commented on web/src/components/ArticleCell/ArticleCell.tsx
> +export const Loading = () => <div>Loading...</div>
use chakra for loading, empty, and failure as well

2024-01-03 06:52 UTC, amnanwar commented on web/src/pages/HomePage/HomePage.tsx
> +// import { Heading } from '@chakra-ui/react'
you can remove these if its not being used

2024-01-04 06:56 UTC, samra-pullflow commented on api/src/lib/post_manager.ts
> +export const posts: QueryResolvers['posts'] = () => {
handling in another branch

2024-01-04 06:57 UTC, samra-pullflow commented on api/src/services/posts/posts.ts
>    return db.post.findUnique({
handling in another branch

2024-01-04 06:57 UTC, samra-pullflow commented on web/src/components/ArticleCell/ArticleCell.tsx
> +export const Loading = () => <div>Loading...</div>
handling in another branch

2024-01-04 06:57 UTC, samra-pullflow commented on api/src/lib/posts.test.ts
> +import {
handling in another branch

2024-01-04 07:11 UTC, amna-pullflow approved these changes
Looks good, please remove the two comments related to postgres in the next PR

2024-01-04 08:01 UTC, merged